export const CATEGORIES = [
  {
    id: 'guitarra',
    nom: 'Guitarra Elèctrica',
    icon: '🎸',
    prompts: {
      basic: 'Ets un professor de guitarra elèctrica per a principiants. Dona un consell pràctic, concret i motivador per a algú que porta menys de 6 mesos tocant. El consell ha de ser sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un guitarrista professional amb 20 anys d\'experiència. Dona un consell intermedi per a algú amb 1-3 anys d\'experiència sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un guitarrista virtuós especialitzat en tècniques avançades. Dona un consell professional i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com col·locar correctament els dits als acords bàsics (La, Mi, Re)',
        'la postura del cos i la posició de la guitarra assegut',
        'com fer un escalfament de dits efectiu',
        'la importància del metrònom per a principiants',
        'com canviar d\'acord de manera fluida',
        'com evitar el soroll no desitjat de les cordes mudes',
        'la diferència entre púa i dits i quan usar cadascun',
        'com afinar la guitarra de memòria sense afinador',
        'els primers patrons de pentatònica per a principiants',
        'com practicar 15 minuts diaris de manera efectiva',
      ],
      intermediate: [
        'tècnica de bending precís i com entrenar-la',
        'vibrato de mà esquerra i com aconseguir expressivitat',
        'alternate picking a altes velocitats',
        'legato (hammer-ons i pull-offs) en escales',
        'palm muting per a riffs de rock i metal',
        'com improvisar sobre una progressió de blues',
        'la tècnica del hybrid picking (púa i dits)',
        'com aconseguir un so net en posicions altes del mástil',
        'sincronització entre les dues mans en arpegis',
        'ús expressiu del whammy bar',
      ],
      advanced: [
        'tapping de dues mans en escales modals',
        'sweep picking en arpejos de 5 cordes',
        'economia de moviment en escales a alta velocitat',
        'improvisació sobre progressions amb canvis modals',
        'com aconseguir un so professional en directe amb pedals',
        'tècnica de string skipping per a melodíes no convencionals',
        'ús de l\'escala diminuïda i augmentada en jazz-rock',
        'eight-finger tapping en estil Van Halen',
        'com gravar guitarra en casa amb so professional',
        'frasseig melòdic sobre canvis d\'acords no diatònics',
      ],
    },
  },
  {
    id: 'salut',
    nom: 'Salut',
    icon: '🏥',
    prompts: {
      basic: 'Ets un metge de capçalera amable. Dona un consell senzill de salut preventiva sobre: {topic}. Evita diagnòstics. Respon en Català, en 3-5 frases accessibles.',
      intermediate: 'Ets un especialista en medicina preventiva. Dona un consell intermedi per a algú que ja té uns hàbits bàsics sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un metge especialista en optimització de la salut. Dona un consell avançat basat en evidència sobre: {topic}. Respon en Català, en 3-5 frases tècniques però comprensibles.',
    },
    topics: {
      basic: [
        'la importància de beure prou aigua al llarg del dia',
        'com millorar la qualitat del son amb rutines nocturnes',
        'per què caminar 30 minuts diaris canvia la salut',
        'com reduir el consum de sucre de manera gradual',
        'la importància dels àpats a hores fixes',
        'com gestionar l\'estrès diari amb tècniques senzilles de respiració',
        'per què és important l\'exposició solar moderada',
        'hàbits posturals per evitar dolors d\'esquena',
        'com rentar-se les mans correctament per evitar infeccions',
        'la importància de les revisions mèdiques preventives anuals',
      ],
      intermediate: [
        'nutrició funcional: aliments antiinflamatoris',
        'periodització de l\'exercici per maximitzar recuperació',
        'com millorar la variabilitat de la freqüència cardíaca (HRV)',
        'l\'impacte del microbioma intestinal en la salut general',
        'tècniques de gestió de l\'estrès crònic: mindfulness i meditació',
        'optimització del son: fases REM i son profund',
        'com estructurar una dieta rica en fibra i proteïna',
        'el paper dels omega-3 en la salut cardiovascular',
        'exercicis de mobilitat per prevenir lesions en adults actius',
        'com interpretar els resultats d\'una analítica bàsica',
      ],
      advanced: [
        'cronobiologia i com els ritmes circadiants afecten el metabolisme',
        'biomarcadors de longevitat: NAD+, IGF-1, senescència cel·lular',
        'protocols de dejú intermitent basat en evidència científica',
        'supplementació avançada: creatina, magnesI, vitamina D3+K2',
        'la via mTOR i la seua relació amb envelliment i muscle',
        'hormesi: com l\'estrès positiu (sauna, fred, exercici) millora la salut',
        'epigenètica i estil de vida: com els nostres hàbits modifiquen l\'expressió gènica',
        'avaluació de la composició corporal més enllà del pes: DEXA i impedanciometria',
        'el paper del cortisol crònic en la salut metabòlica',
        'medicina personalitzada basada en genòmica nutricional',
      ],
    },
  },
  {
    id: 'tecnologia',
    nom: 'Tecnologia',
    icon: '💻',
    prompts: {
      basic: 'Ets un professor de tecnologia per a persones no tècniques. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un enginyer de software. Dona un consell intermedi sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un arquitecte de sistemes sènior. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com protegir les contrasenyes amb un gestor de contrasenyes',
        'com evitar estafes i phishing al correu electrònic',
        'per què és important actualitzar el sistema operatiu',
        'com fer còpies de seguretat dels teus arxius importants',
        'com millorar la velocitat del mòbil netejant la caché',
        'consells per a una bona higiene digital (privacitat a les xarxes)',
        'com usar Google de manera més eficient amb cerca avançada',
        'com configurar l\'autenticació en dos factors (2FA)',
        'per què cal desconnectar-se del wifi públic per seguretat',
        'com organitzar millor els arxius al núvol (Drive, iCloud)',
      ],
      intermediate: [
        'automatització de tasques repetitives amb scripts de shell',
        'com usar Git de manera efectiva en un projecte en solitari',
        'productivitat amb eines com Notion, Obsidian o Linear',
        'introducció als contenidors Docker per a desenvolupadors',
        'com configurar un entorn de desenvolupament local eficient',
        'bones pràctiques de seguretat en APIs REST',
        'com depurar errors de xarxa amb les DevTools del navegador',
        'introducció als webhooks i com integrar serveis web',
        'com llegir i aprofitar la documentació tècnica d\'una API',
        'ús de variables d\'entorn per gestionar secrets en projectes',
      ],
      advanced: [
        'patrons de disseny per a sistemes distribuïts (CQRS, Event Sourcing)',
        'optimització de consultes en bases de dades relacionals',
        'estratègies de caché a múltiples nivells (CDN, Redis, memòria)',
        'seguretat avançada: OWASP Top 10 i com mitigar-los',
        'observabilitat: traces distribuïdes, mètriques i logs centralitzats',
        'arquitectura de microserveis: quan té sentit i quan no',
        'kubernetes: gestió de pods, services i ingress controllers',
        'optimització de rendiment en aplicacions React/Next.js',
        'CI/CD avançat: blue-green deployments i feature flags',
        'anàlisi de complexitat algorítmica i optimització de codi crític',
      ],
    },
  },
  {
    id: 'huerto',
    nom: 'Huerto Ecològic',
    icon: '🌱',
    prompts: {
      basic: 'Ets un agricultor ecològic amb experiència. Dona un consell bàsic per a un principiant sobre: {topic}. Respon en Català, en 3-5 frases pràctiques.',
      intermediate: 'Ets un expert en permacultura. Dona un consell intermedi per a algú amb experiència bàsica en jardineria sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un agrònom especialitzat en agricultura regenerativa. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'quines plantes aromàtiques són les millors per al balcó',
        'com preparar la terra d\'un test per plantar de zero',
        'quanta aigua necessiten les tomaqueres a l\'estiu',
        'com sembrar enciams i tindre collita tot l\'any',
        'per què és important el drenatge en els tests',
        'quines plantes s\'adapten millor a l\'ombra parcial',
        'com fer un petit compostador casolà amb restes orgàniques',
        'quan i com trasplantar una plàntula al seu test definitiu',
        'com reconèixer si a una planta li falta o li sobra aigua',
        'els errors més comuns d\'un principiant en l\'hort',
      ],
      intermediate: [
        'rotació de cultius per evitar l\'esgotament del sòl',
        'compostatge avançat: relació carboni/nitrogen òptima',
        'control de pugons i àcars amb preparats naturals',
        'associació de cultius beneficiosa: tomàquets, alfàbrega i ceba',
        'com fer un acolxat (mulching) eficient per conservar la humitat',
        'introducció al cultiu en bancals elevats (raised beds)',
        'preparació de te de compost per fertilitzar de manera natural',
        'com gestionar les malalties fúngiques sense productes químics',
        'sembra per lluna: fonaments i aplicació pràctica',
        'com fer esqueixos i multiplicar plantes de manera vegetativa',
      ],
      advanced: [
        'biofertilitzants: lactobacilos, trichoderma i micorizes',
        'tècnica de sòl viu: fungus networks i biologia del sòl',
        'sistemes agroforestals: integrar arbres fruiters en l\'hort',
        'permacultura avançada: zones, sectors i disseny de paisatge productiu',
        'agricultura sinergètica de Masanobu Fukuoka aplicada a l\'hort urbà',
        'anàlisi de sòl avançada: pH, CIC, i nutrients disponibles',
        'biodynamia: preparats 500 i 501 i la seua aplicació',
        'disseny de sistemes d\'irrigació per degoteig eficients',
        'producció de llavors pròpies i conservació del patrimoni genètic',
        'integració de bestiar menor (gallines, cucs) en sistemes d\'hort tancat',
      ],
    },
  },
  {
    id: 'estructures',
    nom: 'Estructures Metàl·liques',
    icon: '🏗️',
    prompts: {
      basic: 'Ets un tècnic en construcció metàl·lica. Dona un consell bàsic per a algú que s\'inicia sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un enginyer estructural. Dona un consell intermedi per a tècnics amb experiència sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un enginyer estructural sènior especialitzat en estructures metàl·liques. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'els tipus de perfils metàl·lics més comuns (HEB, IPE, UPN)',
        'com llegir un plànol estructural bàsic',
        'la diferència entre acer S235 i S355',
        'les eines bàsiques d\'un taller de construcció metàl·lica',
        'com mesurar i marcar perfils metàl·lics correctament',
        'les normes bàsiques de seguretat en un taller metàl·lic',
        'conceptes bàsics de soldadura: tipus i aplicacions',
        'per què és important la protecció anticorrosió (galvanitzat, pintura)',
        'la diferència entre una unió soldada i una cargolada',
        'com interpretar una fulla d\'especificació tècnica d\'un perfil',
      ],
      intermediate: [
        'càlcul de moment flector en biga simplement recolzada',
        'disseny de unions cargolades per a estructures de classe 2',
        'protecció al foc d\'estructures metàl·liques: normativa CTE-SI',
        'el fenomen del vinclament (pandeo) i com prevenir-lo',
        'soldadura en angle: dimensions, control de qualitat i assajos',
        'coordinació entre estructura metàl·lica i façana',
        'càlcul de plaques base i ancoratges a fonamentació',
        'introducció al programari CYPE per a càlcul d\'estructures',
        'unitats i codificació en plànols d\'estructura metàl·lica',
        'el paper de l\'enginyer de control de qualitat en obra metàl·lica',
      ],
      advanced: [
        'anàlisi no lineal geomètrica i material en estructures metàl·liques',
        'disseny sísmic d\'estructures metàl·liques: ductilitat i classes de secció',
        'fatiga en estructures metàl·liques: càlcul i categories de detall',
        'optimització topològica amb Grasshopper i Karamba3D',
        'estructures tensegritat i cable-stayed: principis de disseny',
        'modelització per elements finits (FEM) d\'unions complexes',
        'disseny de cobertes lleugeres d\'acer: formes funiculars',
        'connexions semi-rígides: comportament moment-rotació i implicacions',
        'control de qualitat avançat en soldadura: END i certificació EN 1090',
        'BIM aplicat a estructures metàl·liques: Tekla Structures i IFC',
      ],
    },
  },
  {
    id: 'ia',
    nom: 'Intel·ligència Artificial',
    icon: '🤖',
    prompts: {
      basic: 'Ets un divulgador de IA per al gran públic. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un professional de IA. Dona un consell intermedi sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un investigador en IA. Dona un consell avançat i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com escriure prompts clars per obtenir millors respostes de ChatGPT o Claude',
        'com usar la IA per resumir documents llargs',
        'com evitar que la IA t\'inventi informació (al·lucinacions)',
        'com usar la IA per aprendre un tema nou de manera guiada',
        'consells per usar la IA de manera segura i privada',
        'com usar la IA per corregir i millorar textos en català',
        'les millors eines d\'IA gratuïtes per a ús quotidià',
        'com usar la IA per preparar presentacions i reunions',
        'per què és important verificar sempre la informació que dona la IA',
        'com usar la IA per crear contingut a les xarxes socials',
      ],
      intermediate: [
        'tècniques avançades de prompt engineering: chain-of-thought i few-shot',
        'com avaluar i comparar models d\'IA per a una tasca específica',
        'integració d\'IA en fluxos de treball empresarials amb APIs',
        'casos d\'ús de la IA en anàlisi de dades i reporting automatitzat',
        'com usar embedding models per a cerca semàntica',
        'introducció als agents d\'IA i quan té sentit usar-los',
        'com construir un pipeline RAG senzill per als teus documents',
        'avaluació de la qualitat de les respostes d\'un LLM',
        'IA multimodal: com usar models amb imatges i documents',
        'com gestionar costos d\'API d\'IA en producció',
      ],
      advanced: [
        'fine-tuning de models de llenguatge: quan té sentit vs. prompting',
        'arquitectura de sistemes RAG avançats: reranking i query expansion',
        'agents autònoms multi-pas: planificació i execució d\'eines',
        'avaluació sistemàtica de LLMs: benchmarks, evals i mètriques',
        'optimització d\'inferència: quantització, batching i KV cache',
        'seguretat en sistemes d\'IA: prompt injection i jailbreaking',
        'tendències actuals en recerca: models de raonament i test-time compute',
        'arquitectures mixture-of-experts (MoE) i les seues implicacions',
        'construcció de pipelines d\'entrenament continu (RLHF/DPO)',
        'memòria a llarg termini en agents: vector stores i grafos de coneixement',
      ],
    },
  },
  {
    id: 'piano',
    nom: 'Piano',
    icon: '🎹',
    prompts: {
      basic: 'Ets un professor de piano per a principiants. Dona un consell pràctic i motivador per a algú que porta menys de 6 mesos estudiant sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un pianista professional. Dona un consell intermedi per a algú amb 1-3 anys d\'experiència sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un concertista de piano amb formació al conservatori. Dona un consell avançat i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'la postura correcta davant del piano i la posició de les mans',
        'com llegir les notes a la clau de Sol per a principiants',
        'la coordinació entre la mà dreta i l\'esquerra en peces senzilles',
        'com practicar lentament amb metrònom per fixar una peça',
        'els acords bàsics de Do, Fa i Sol en posició fonamental',
        'com afrontar la memorització d\'una peça curta',
        'la importància d\'escalfar els dits abans de practicar',
        'com llegir les notes de la clau de Fa (mà esquerra)',
        'els patrons rítmics bàsics: negres, corxeres i blanques',
        'com organitzar una sessió de pràctica de 20 minuts eficaça',
      ],
      intermediate: [
        'tècnica de legato i staccato: diferències i aplicació expressiva',
        'com abordar peces amb canvis sobtats de dinàmica',
        'pedal de sustain: quan i com usar-lo sense embrutar el so',
        'tècnica de les escales majors i menors a dues mans',
        'arpejos i inversions d\'acords en la mà esquerra',
        'com practicar passatges difícils amb variacions rítmiques',
        'introducció a la lectura a primera vista (sight-reading)',
        'ornaments bàsics: el trino, el mordent i l\'apoyatura',
        'articulació en estil barroc vs. estil romàntic',
        'com treballar la independència de les dues mans en contrapunt',
      ],
      advanced: [
        'mecanisme del doble repic (double escapement) i velocitat en trèmols',
        'voicing: com fer sobresortir la melodia dins d\'un acord',
        'tècnica de Chopin: tempo rubato i pes natural del braç',
        'polifonia en Bach: com escoltar i interpretar cada veu per separat',
        'octaves i acords forts sense tensió: tècnica de Liszt',
        'anàlisi harmònica aplicada a la interpretació expressiva',
        'memorització profunda: estructural, tàctil, auditiva i analítica',
        'preparació per a una actuació en públic: gestió dels nervis',
        'improvisació sobre progressions de jazz al piano clàssic',
        'registre de la mà esquerra: baix d\'Alberti vs. acompanyament modern',
      ],
    },
  },
  {
    id: 'finances',
    nom: 'Finances Personals',
    icon: '💰',
    prompts: {
      basic: 'Ets un assessor financer per a persones que comencen a gestionar els seus diners. Dona un consell pràctic i accessible sobre: {topic}. Evita termes complexos. Respon en Català, en 3-5 frases.',
      intermediate: 'Ets un planificador financer personal. Dona un consell intermedi per a algú que ja té uns estalvis bàsics sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un expert en inversions i planificació financera. Dona un consell avançat basat en estratègia sobre: {topic}. Respon en Català, en 3-5 frases tècniques però comprensibles.',
    },
    topics: {
      basic: [
        'com fer un pressupost mensual senzill i mantenir-lo',
        'la regla del 50/30/20 per gestionar els ingressos',
        'per què és essencial tenir un fons d\'emergència',
        'com identificar i eliminar despeses innecessàries',
        'la diferència entre deute bo i deute dolent',
        'per què cal comparar preus i llegir la lletra petita',
        'com estalviar automàticament amb transferències programades',
        'la importància de pagar les targetes de crèdit a final de mes',
        'com evitar les trampes de les subscripcions oblidades',
        'per què és important entendre els teus rebuts i extractes bancaris',
      ],
      intermediate: [
        'inversió indexada: ETFs i fons de baix cost (Vanguard, iShares)',
        'la màgia de l\'interès compost i per què el temps importa',
        'diversificació de cartera: renta fixa vs. renta variable',
        'pla de pensions vs. fons d\'inversió: quan convé cada un',
        'com declarar correctament les inversions a l\'IRPF',
        'fiscalitat dels estalvis: comptes remunerats i fons',
        'inversió en immobles: avantatges i riscos reals',
        'com avaluar si un crèdit hipotecari és favorable',
        'estratègia de "bola de neu" vs. "allau" per pagar deutes',
        'seguros essencials que tothom hauria de considerar',
      ],
      advanced: [
        'construcció d\'una cartera permanent: oro, accions, bons i cash',
        'tax-loss harvesting: com aprofitar les pèrdues per reduir impostos',
        'inversió en dividend aristocrats per a ingressos passius',
        'anàlisi fonamental d\'empreses per a inversió a llarg termini',
        'FIRE (Financial Independence, Retire Early): estratègies i taxes de retirada',
        'inversió en actius alternatius: REITs, crowdlending, commodities',
        'gestió del risc: correlació d\'actius i cobertura (hedging)',
        'optimització fiscal avançada: holdings i estructures societàries',
        'planificació de la jubilació amb simulació de Monte Carlo',
        'inversió responsable (ESG): criteris i rendiment comparat',
      ],
    },
  },
  {
    id: 'cuina',
    nom: 'Cuina',
    icon: '🍳',
    prompts: {
      basic: 'Ets un cuiner amable que ensenya a persones que gairebé no han cuinat mai. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un cuiner professional. Dona un consell intermedi per a algú que ja domina les tècniques bàsiques sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un xef amb formació gastronòmica d\'alt nivell. Dona un consell avançat i tècnic sobre: {topic}. Respon en Català, en 3-5 frases precises.',
    },
    topics: {
      basic: [
        'com tallar una ceba sense plorar i amb seguretat',
        'la diferència entre fregir, saltejat i confitar',
        'com saber si una paella està prou calenta abans d\'afegir ingredients',
        'per què cal eixugar bé els aliments abans de fregir-los',
        'com coure l\'arròs blanc perfecte sense que s\'enganxi',
        'les espècies bàsiques que no haurien de faltar a la cuina',
        'com interpretar una recepta i preparar el mise en place',
        'la regla del repòs: per què la carn cal deixar-la reposar',
        'com fer una vinagreta equilibrada (àcid, greix, sal)',
        'com evitar que els ous remenats quedin secs i de goma',
      ],
      intermediate: [
        'tècnica del sofreginat: temperatura, ordre i temps per construir sabors',
        'com fer un brou fosc de carn amb os torrat',
        'la tècnica del sous-vide i quan és útil a casa',
        'com aconseguir una salsa cremosa sense tallar-se',
        'fermentació bàsica: kimchi, iogurt i pa de massa mare',
        'com caramelitzar cebes i fondres lentament per a màxim sabor',
        'la tècnica del blanqueig i xoc tèrmic per conservar el color dels vegetals',
        'com ajustar l\'acidesa i el sal en un plat acabat',
        'coccions al forn: convecció vs. calor tradicional i diferències',
        'com crear una emulsió estable: maionesa, hollandesa, aioli',
      ],
      advanced: [
        'tècniques de cuina molecular: esferificació, gels i escumes',
        'Maillard vs. caramel·lització: química i control de cada reacció',
        'com construir un menú de degustació equilibrat en sabors i textures',
        'cuina al buit de baixa temperatura: barems de temps i temperatura per proteïna',
        'deconstrucció d\'un plat clàssic: tècnica i concepte',
        'com treballar el gluten en pastisseria i pa artesà',
        'reducció i concentració de sabors: demi-glace i consommé',
        'maridatge avançat: com el greix, l\'acid i els tanins interaccionen',
        'tècnica de trempat (mise en place) en restaurant: eficiència i qualitat',
        'fermentació avançada: koji, miso i salses fermentades',
      ],
    },
  },
  {
    id: 'fitness',
    nom: 'Fitness',
    icon: '🏋️',
    prompts: {
      basic: 'Ets un entrenador personal per a persones que comencen a fer exercici. Dona un consell pràctic i motivador sobre: {topic}. Evita tecnicismes. Respon en Català, en 3-5 frases.',
      intermediate: 'Ets un entrenador personal certificat. Dona un consell intermedi per a algú que entrena regularment sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un preparador físic d\'alt rendiment. Dona un consell avançat i basat en evidència sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com fer una sentadilla (squat) correctament sense danyar els genolls',
        'per quina raó l\'escalfament previ és imprescindible',
        'com organitzar 3 dies d\'entrenament a la setmana sent principiant',
        'la importància del son per a la recuperació muscular',
        'com evitar les lesions més comunes a principiants',
        'per quina raó la nutrició importa tant com l\'exercici',
        'com fer una planxa (plank) correctament per enfortir el core',
        'la diferència entre cardio i entrenament de força',
        'com hidratat-se correctament durant l\'exercici',
        'com mantenir la motivació durant els primers 3 mesos',
      ],
      intermediate: [
        'periodització lineal vs. undulating: quan usar cadascuna',
        'el principi de sobrecàrrega progressiva aplicat al teu entrenament',
        'entrenament de mobilitat: per quin motiu és tan important com la força',
        'nutrició peritraining: carbohidrats antes i proteïna post-entrenament',
        'com integrar el HIIT sense sobreentrenar',
        'tècnica del hip hinge per a pesos morts i kettlebell swings',
        'gestió de la fatiga: com saber quan descansar i quan forçar',
        'control del tempo en els exercicis per maximitzar la tensió mecànica',
        'entrenament de l\'empenta vertical vs. horitzontal per al tren superior',
        'com analitzar el teu progrés amb mètriques més allà del pes',
      ],
      advanced: [
        'blocs d\'acumulació, intensificació i realització en periodització avançada',
        'entrenament de força màxima: triples, dobles i simples pesats',
        'RPE i RIR: autorregulació de la intensitat en els entrenaments',
        'entrenament oclusiu (BFR training): protocoles i aplicacions',
        'anàlisi biomecànica de l\'arrancada i dos temps olímpics',
        'estratègies de nutrició per a recomposició corporal sense fase de volum',
        'gestió de la fatiga central vs. perifèrica en esportistes avançats',
        'programació de la competició de powerlifting: peaking i tapering',
        'com interpretar dades d\'HRV per ajustar l\'entrenament diari',
        'suplementació basada en evidència: creatina, beta-alanina, cafeïna',
      ],
    },
  },
  {
    id: 'fotografia',
    nom: 'Fotografia',
    icon: '📸',
    prompts: {
      basic: 'Ets un fotògraf que ensenya a principiants. Dona un consell pràctic sobre: {topic}. Parla en termes senzills. Respon en Català, en 3-5 frases.',
      intermediate: 'Ets un fotògraf professional. Dona un consell intermedi per a algú que ja entén els controls manuals de la càmera sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un fotògraf de prestigi amb exposicions internacionals. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques i conceptuals.',
    },
    topics: {
      basic: [
        'el triangle d\'exposició: diafragma, velocitat i ISO en paraules senzilles',
        'com composar millor una foto amb la regla dels terços',
        'per quina raó la llum natural és la millor mestra per a principiants',
        'com treure millors fotos amb el mòbil: tocs bàsics',
        'la diferència entre mode automàtic, prioritat d\'apertura i manual',
        'com evitar fotos mogudes en condicions de poca llum',
        'la importància del punt de vista i l\'alçada en una foto',
        'com fer un retrat senzill amb un fons desenfocado (bokeh)',
        'per quina raó cal mirar bé el fons abans de disparar',
        'com organitzar i fer còpies de seguretat de les teves fotos',
      ],
      intermediate: [
        'llum de l\'hora daurada i hora blava: com aprofitar-les',
        'histograma: com llegir-lo i corregir l\'exposició de forma fiable',
        'focuseig manual vs. autofocus: modes AF i quan usar cadascun',
        'fotografia RAW vs. JPG: diferències i flux de treball',
        'composició avançada: línies guies, marcs naturals i espai negatiu',
        'flash extern: mode TTL i sincronització amb llum ambient',
        'edició amb Lightroom: flux de treball i ajustos essencials',
        'fotografia en baixa llum: ISO alt i reducció de soroll',
        'retrat amb finestra: com modelar la llum natural a l\'interior',
        'fotografia de paisatge: filtres ND, trípode i llarga exposició',
      ],
      advanced: [
        'construcció d\'un estil visual propi: coherència i intenció',
        'il·luminació d\'estudi avançada: Rembrandt, split, butterfly',
        'fotografia de producte: superfícies reflectants i control de llum',
        'edició de color avançada: corbes, HSL i color grading cinematogràfic',
        'fotografia documental i fotoperiodisme: ètica i narració visual',
        'el concepte de moment decisiu de Cartier-Bresson aplicat avui',
        'construcció d\'un portafoli editorial que expliqui una història',
        'impressió de qualitat: perfils ICC, paper i calibratge del monitor',
        'composició simbòlica: com la cultura modela el que fem llegible',
        'crítica de fotografia: com analitzar i aprendre de les grans obres',
      ],
    },
  },
  {
    id: 'productivitat',
    nom: 'Productivitat',
    icon: '🧠',
    prompts: {
      basic: 'Ets un coach de productivitat per a persones que volen organitzar-se millor. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases accessibles.',
      intermediate: 'Ets un expert en gestió del temps i sistemes personals. Dona un consell intermedi per a algú que ja usa eines digitals bàsiques sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un consultor d\'organització personal i empresarial. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases precises.',
    },
    topics: {
      basic: [
        'com fer una llista de tasques que realment funcioni',
        'la tècnica Pomodoro: com i quan usar-la',
        'per quina raó cal planificar el dia anterior a la nit',
        'com eliminar les distraccions digitals mentre treballes',
        'la regla dels 2 minuts per a tasques petites',
        'per quina raó el multitasking és contraproduent',
        'com identificar les teves 3 tasques importants del dia (MIT)',
        'la importància de les pauses programades per mantenir el focus',
        'com crear un espai de treball que ajudi la concentració',
        'per quina raó és útil revisar la setmana cada divendres',
      ],
      intermediate: [
        'GTD (Getting Things Done): els 5 passos essencials',
        'com crear un segon cervell digital amb Obsidian o Notion',
        'time-blocking: com assignar blocs de temps a cada tipus de tasca',
        'matriu d\'Eisenhower: urgent/important per prioritzar de debò',
        'com gestionar el correu electrònic sense que controli el teu dia',
        'batching de tasques similars per reduir el canvi de context',
        'revisió setmanal profunda: elements clau i rutina recomanada',
        'com crear sistemes de captura per no perdre cap idea',
        'deep work vs. shallow work: com protegir el temps de qualitat',
        'gestió de projectes personals amb Kanban o llista d\'àrees',
      ],
      advanced: [
        'disseny del sistema personal d\'organització: àrees, projectes, recursos',
        'optimització del flux de treball cognitiu: quan fer cada tipus de tasca',
        'estratègies per a la gestió de l\'energia personal, no del temps',
        'building a second brain (PARA method): implementació completa',
        'automatitzar fluxos de treball amb Zapier, Make o scripts propis',
        'gestió de l\'atenció: focus profund i pràctiques de neurociència',
        'disseny de rituels de transició per separar treball i descans',
        'com delegar i crear sistemes perquè les coses passin sense tu',
        'avaluació anual personal: OKRs i revisió de rols vitals',
        'combinar Zettelkasten i gestió de projectes en un sistema unificat',
      ],
    },
  },
  {
    id: 'idiomes',
    nom: 'Idiomes',
    icon: '🗣️',
    prompts: {
      basic: 'Ets un professor de idiomes per a principiants. Dona un consell pràctic per aprendre un idioma nou de manera eficaç sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un lingüista i poliglota. Dona un consell intermedi per a algú que ja té un nivell bàsic en un segon idioma sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un expert en adquisició de segones llengues i professor universitari. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com aprendre les primeres 500 paraules d\'un idioma de manera eficient',
        'la importància de l\'escolta activa des del primer dia',
        'com usar Anki (o flashcards) per a memòria a llarg termini',
        'per quina raó és millor aprendre frases que paraules aïllades',
        'com crear hàbits d\'estudi de 15 minuts diaris que persisteixin',
        'per quina raó no cal esperar a ser "bo" per parlar',
        'com aprofitar sèries, músics i podcasts en l\'idioma objectiu',
        'la diferència entre aprendre gramàtica de manera activa vs. passiva',
        'com trobar intercanvis de conversa (tandem) gratuïts',
        'per quina raó l\'immersió parcial en casa és possible i eficaç',
      ],
      intermediate: [
        'input comprensible: la hipòtesi de Krashen aplicada a l\'estudi',
        'com superar la barrera del nivell B1 i deixar d\'estancar-se',
        'shadowing: tècnica per millorar pronunciació i fluïdesa alhora',
        'extensive reading: com llegir textos fàcils per automatitzar gramàtica',
        'com tenir converses reals quan les perds o no entens alguna cosa',
        'adquisició de col·locacions (collocations) per sonar natural',
        'la importància del output forçat (escriptura, parla) per aprendre',
        'com analitzar errors propis i convertir-los en aprenentatge',
        'estratègies per a la comprensió oral: diferències dialectals',
        'com construir vocabulari en àrees específiques (feina, viatge, cultura)',
      ],
      advanced: [
        'SRS avançat: optimització dels intervals de repàs per a retencó màxima',
        'com aconseguir un accent neutre o natiu: tècniques fonètiques',
        'diferència entre nivell C1 i parlar com un natiu: el gap cognitiu',
        'aprenentatge de múltiples idiomes simultanis: quan és viable',
        'anàlisi contrastiva entre dues llengues per evitar interferències',
        'immersió total: com organitzar un mes d\'immersió real o virtual',
        'registres i dialectes: com adaptar el teu idioma al context social',
        'estudi de la llengua escrita formal vs. oral col·loquial',
        'adquisició tardana d\'una llengua: mites i realitats neurològiques',
        'com mantenir un idioma après quan ja no el practiques activament',
      ],
    },
  },
  {
    id: 'disseny',
    nom: 'Disseny',
    icon: '🎨',
    prompts: {
      basic: 'Ets un dissenyador que ensenya els fonaments a persones sense experiència. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un dissenyador gràfic o UX professional. Dona un consell intermedi per a algú que ja coneix les eines bàsiques sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un director creatiu o dissenyador sènior. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques i conceptuals.',
    },
    topics: {
      basic: [
        'els 4 principis bàsics del disseny: contrast, repetició, alineació i proximitat (CRAP)',
        'com triar una paleta de colors harmònica sense ser expert',
        'la importància de l\'espai en blanc (white space) en un disseny net',
        'com combinar dos tipus de lletra sense que xoquin',
        'per quina raó la jerarquia visual guia l\'ull del lector',
        'com usar Canva per crear dissenys professionals de manera senzilla',
        'la diferència entre disseny vectorial (SVG) i mapa de bits (PNG/JPG)',
        'per quina raó la consistència visual és la base de qualsevol marca',
        'com adaptar un disseny per a mòbil i per a escriptori',
        'com fer un mood board per definir l\'estètica d\'un projecte',
      ],
      intermediate: [
        'sistemes de graella (grid) per a disseny web i editorial',
        'psicologia del color aplicada al disseny de marca',
        'tipografia avançada: tracking, kerning, leading i jerarquia',
        'disseny UX: fluxos d\'usuari i wireframes de baixa fidelitat',
        'com construir un sistema de disseny bàsic amb tokens',
        'principis de Gestalt aplicats al disseny visual',
        'branding: diferència entre identitat, marca i comunicació',
        'com fer una presentació visual impactant (Figma, Keynote)',
        'iconografia consistent: quan usar icones i com',
        'accessibilitat en disseny: contrast, mida i llegibilitat (WCAG)',
      ],
      advanced: [
        'disseny de sistemes: atomic design i tokens de disseny a escala',
        'direction creativa: com articul·lar i defensar una visió estètica',
        'motion design: principis d\'animació aplicats a interfícies',
        'estratègia de marca: posicionament, to de veu i identitat visual unificats',
        'disseny d\'experiència d\'usuari: research, test d\'usabilitat i iteració',
        'tipografia expressiva: quan trencar les regles i com fer-ho bé',
        'co-disseny amb IA: workflows amb Midjourney, Firefly i Figma AI',
        'disseny editorial avançat: maquetació de llibres i revistes amb InDesign',
        'narrativa visual: storytelling a través del disseny de marca',
        'com construir i presentar un portafoli de disseny sènior',
      ],
    },
  },
  {
    id: 'kitesurf',
    nom: 'Kitesurf',
    icon: '🪁',
    prompts: {
      basic: 'Ets un instructor de kitesurf certificat IKO. Dona un consell pràctic i segur per a un principiant sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un instructor de kitesurf amb 10 anys d\'experiència. Dona un consell intermedi per a algú que ja sap navegar però vol millorar sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un rider professional de kitesurf i entrenador de competició. Dona un consell avançat i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com interpretar les condicions de vent per a un principiant (direcció, velocitat)',
        'les zones de seguretat al voltant del cometa (zona de poder i zona neutra)',
        'com muntar i desmontar l\'equip de kitesurf de manera segura',
        'la tècnica del body drag per recuperar la taula a l\'aigua',
        'com activar el sistema de seguretat (quick release) correctament',
        'per què és perillós fer kitesurf amb vent off-shore',
        'com pilotar el cometa en la zona de vent (finestra de vol)',
        'els senyals de mà per comunicar-se a la platja',
        'com escollir la talla de cometa adequada per al teu pes i el vent',
        'les regles de prioritat entre riders al water',
      ],
      intermediate: [
        'la tècnica del water start: passos i errors comuns',
        'com fer un halte (stop) controlat al water',
        'tècnica del tack (canvi de direcció cap al vent)',
        'tècnica del jibe (canvi de direcció amb el vent)',
        'com generar velocitat i mantenir el contakt amb l\'aigua',
        'com navegar en upwind (contra el vent)',
        'el relaunch del cometa des de l\'aigua',
        'com usar la barra per controlar la potència del cometa (sheet in/out)',
        'tècnica de riding amb taula twintip en waves',
        'com preparar i gestionar un primer salt petit',
      ],
      advanced: [
        'tècnica del jump: pop, timing i control del cometa en aire',
        'el megaloop: iniciació segura i progressió',
        'tricks unhooked bàsics: railey i back roll unhooked',
        'wave riding amb kitesurf: lectura de l\'onada i timing',
        'kitesurf amb foil: diferències tècniques i adaptació',
        'tècnica del board-off en salts',
        'com optimitzar el trim i la posició de les ancoratges del bar',
        'progressió en kiteloop: control del pull i seguretat',
        'com entrenar kitesurf fora de l\'aigua (visualització, gym)',
        'preparació per a competicions de freestyle: judging criteria',
      ],
    },
  },
  {
    id: 'vscode',
    nom: 'VS Code & IA',
    icon: '🤖',
    prompts: {
      basic: 'Ets un desenvolupador que ensenya eines d\'IA i VS Code a principiants. Dona un consell pràctic sobre: {topic}. Explica-ho com si fós per a algú que mai ha usat aquestes eines. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un desenvolupador avançat que integra eines d\'IA al seu flux de treball diari amb VS Code. Dona un consell intermedi per a algú que ja coneix les bases sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un expert en integració d\'eines d\'IA i automatització amb VS Code. Dona un consell avançat i tècnic sobre: {topic}. Explica arquitectura, configuració i millors pràctiques. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com instal·lar i configurar l\'extensió de Cline a VS Code per primera vegada',
        'què és OpenRouter i com aconseguir una API key per usar models d\'IA',
        'com crear el teu primer agent amb Cline per automatitzar una tasca senzilla',
        'com funciona el sistema de fitxers de Cline per llegir i modificar el teu codi',
        'com donar instruccions clares a Cline per obtenir resultats útils',
        'com usar Cline per explicar codi que no entens',
        'com configurar els models d\'IA a Cline (Claude, GPT, etc.)',
        'com usar Cline per generar documentació bàsica del teu projecte',
        'què és un MCP server i per a què serveix a Cline',
        'com fer que Cline respecti el teu codi existent sense sobreescriure\'l',
      ],
      intermediate: [
        'com crear MCP servers personalitzats per ampliar les capacitats de Cline',
        'com usar Cline amb múltiples models i comparar-ne els resultats',
        'com integrar Cline en un flux de treball amb Git: commits, review i PRs',
        'com configurar OpenRouter per encaminar requests a diferents models segons el cost',
        'com usar Cline per refactoritzar codi de manera segura amb tests',
        'com crear prompts efectius per a Cline que minimitzin errors i al·lucinacions',
        'com gestionar el context de Cline: fitxers oberts, seleccions i instruccions',
        'com usar Cline per depurar errors complexos amb anàlisi de logs i stack traces',
        'com integrar Cline amb bases de dades i APIs externes via MCP',
        'com configurar Cline per treballar amb monorepos i projectes grans',
      ],
      advanced: [
        'com construir un pipeline d\'agents autònoms amb Cline i MCP per a tasques complexes',
        'com optimitzar tokens i costos a OpenRouter: caching, models barats i batching',
        'com crear un sistema de revisió de codi automatitzat amb Cline i GitHub Actions',
        'com implementar RAG local amb Cline per consultar documentació privada del projecte',
        'com configurar Cline per a desplegaments automatitzats a Vercel, Netlify o Railway',
        'com crear MCP servers que exposin APIs de tercers (Slack, Notion, Jira) a Cline',
        'com usar Cline per generar i mantenir tests de càrrega i integració',
        'com dissenyar un workflow de CI/CD assistit per IA amb Cline i OpenRouter',
        'com integrar Cline en un equip: sharing de MCP servers, prompts i configuracions',
        'com construir agents especialitzats amb Cline per a tasques de DevOps i SRE',
      ],
    },
  },
]

export const DIFFICULTIES = [
  { id: 'basic', label: 'Bàsic' },
  { id: 'intermediate', label: 'Intermedi' },
  { id: 'advanced', label: 'Avançat' },
]

function getFormatInstruction(difficulty) {
  if (difficulty === 'basic') {
    return `

Respon SEMPRE amb aquest format exacte, sense cap text addicional fora d'ell:

**Consell:** [escriu aquí el consell principal en 2-4 frases clares i motivadores]

**Exemple pràctic:** [un exemple concret i accionable en 1-2 frases]

**Repte del dia:** [una acció específica que es pugui fer avui, en 1 frase]

Total: entre 4 i 7 frases en total. Sigues concís i directe.`
  }

  if (difficulty === 'intermediate') {
    return `

Respon SEMPRE amb aquest format exacte, sense cap text addicional fora d'ell:

**Consell:** [escriu aquí el consell principal en 3-5 frases amb detalls tècnics i matisos]

**Exemple pràctic:** [un exemple concret i detallat en 2-3 frases]

**Repte del dia:** [una acció específica i mesurable que es pugui fer avui, en 1-2 frases que inclogui un objectiu concret]

Total: entre 6 i 10 frases. Dona profunditat sense ser excessiu.`
  }

  // advanced
  return `

Respon SEMPRE amb aquest format exacte, sense cap text addicional fora d'ell:

**Consell:** [escriu aquí el consell principal en 4-6 frases amb context científic, tècnic o estratègic. Explica per què funciona]

**Exemple pràctic:** [un exemple detallat i tècnic en 2-4 frases que il·lustri el consell]

**Repte del dia:** [una acció específica, mesurable i amb criteri tècnic, en 1-2 frases]

Total: entre 7 i 12 frases. Pots aprofundir amb evidències, mecanismes i matisos. Sigues rigorós.`
}

export function buildPrompt(category, difficulty, topic = null) {
  const chosen = topic ?? category.topics[difficulty][
    Math.floor(Math.random() * category.topics[difficulty].length)
  ]
  return category.prompts[difficulty].replace('{topic}', chosen) + getFormatInstruction(difficulty)
}
