export const CATEGORIES = [
  {
    id: 'guitarra',
    nom: 'Guitarra Elèctrica',
    icon: '🎸',
    prompts: {
      basic: 'Ets un professor de guitarra elèctrica per a principiants. Dona un consell pràctic, concret i motivador per a algú que porta menys de 6 mesos tocant. El consell ha de ser sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un guitarrista professional amb 20 anys d\'experiència. Dona un consell intermedi per a algú amb 1-3 anys d\'experiència sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un guitarrista virtuós especialitzat en tècniques avançades. Dona un consell professional i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com col·locar correctament els dits als acords bàsics (La, Mi, Re)',
        'la postura del cos i la posició de la guitarra assegut',
        'com fer un escalfament de dits efectiu',
        'la importància del metrònom per a principiants',
        'com canviar d\'acord de manera fluida',
        'com evitar el soroll no desitjat de les cordes mudes',
        'la diferència entre púa i dits i quan usar cadascun',
        'com afinar la guitarra de memòria sense afinador',
        'els primers patrons de pentatònica per a principiants',
        'com practicar 15 minuts diaris de manera efectiva',
      ],
      intermediate: [
        'tècnica de bending precís i com entrenar-la',
        'vibrato de mà esquerra i com aconseguir expressivitat',
        'alternate picking a altes velocitats',
        'legato (hammer-ons i pull-offs) en escales',
        'palm muting per a riffs de rock i metal',
        'com improvisar sobre una progressió de blues',
        'la tècnica del hybrid picking (púa i dits)',
        'com aconseguir un so net en posicions altes del mástil',
        'sincronització entre les dues mans en arpegis',
        'ús expressiu del whammy bar',
      ],
      advanced: [
        'tapping de dues mans en escales modals',
        'sweep picking en arpejos de 5 cordes',
        'economia de moviment en escales a alta velocitat',
        'improvisació sobre progressions amb canvis modals',
        'com aconseguir un so professional en directe amb pedals',
        'tècnica de string skipping per a melodíes no convencionals',
        'ús de l\'escala diminuïda i augmentada en jazz-rock',
        'eight-finger tapping en estil Van Halen',
        'com gravar guitarra en casa amb so professional',
        'frasseig melòdic sobre canvis d\'acords no diatònics',
      ],
    },
  },
  {
    id: 'salut',
    nom: 'Salut',
    icon: '🏥',
    prompts: {
      basic: 'Ets un metge de capçalera amable. Dona un consell senzill de salut preventiva sobre: {topic}. Evita diagnòstics. Respon en Català, en 3-5 frases accessibles.',
      intermediate: 'Ets un especialista en medicina preventiva. Dona un consell intermedi per a algú que ja té uns hàbits bàsics sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un metge especialista en optimització de la salut. Dona un consell avançat basat en evidència sobre: {topic}. Respon en Català, en 3-5 frases tècniques però comprensibles.',
    },
    topics: {
      basic: [
        'la importància de beure prou aigua al llarg del dia',
        'com millorar la qualitat del son amb rutines nocturnes',
        'per què caminar 30 minuts diaris canvia la salut',
        'com reduir el consum de sucre de manera gradual',
        'la importància dels àpats a hores fixes',
        'com gestionar l\'estrès diari amb tècniques senzilles de respiració',
        'per què és important l\'exposició solar moderada',
        'hàbits posturals per evitar dolors d\'esquena',
        'com rentar-se les mans correctament per evitar infeccions',
        'la importància de les revisions mèdiques preventives anuals',
      ],
      intermediate: [
        'nutrició funcional: aliments antiinflamatoris',
        'periodització de l\'exercici per maximitzar recuperació',
        'com millorar la variabilitat de la freqüència cardíaca (HRV)',
        'l\'impacte del microbioma intestinal en la salut general',
        'tècniques de gestió de l\'estrès crònic: mindfulness i meditació',
        'optimització del son: fases REM i son profund',
        'com estructurar una dieta rica en fibra i proteïna',
        'el paper dels omega-3 en la salut cardiovascular',
        'exercicis de mobilitat per prevenir lesions en adults actius',
        'com interpretar els resultats d\'una analítica bàsica',
      ],
      advanced: [
        'cronobiologia i com els ritmes circadiants afecten el metabolisme',
        'biomarcadors de longevitat: NAD+, IGF-1, senescència cel·lular',
        'protocols de dejú intermitent basat en evidència científica',
        'supplementació avançada: creatina, magnesI, vitamina D3+K2',
        'la via mTOR i la seua relació amb envelliment i muscle',
        'hormesi: com l\'estrès positiu (sauna, fred, exercici) millora la salut',
        'epigenètica i estil de vida: com els nostres hàbits modifiquen l\'expressió gènica',
        'avaluació de la composició corporal més enllà del pes: DEXA i impedanciometria',
        'el paper del cortisol crònic en la salut metabòlica',
        'medicina personalitzada basada en genòmica nutricional',
      ],
    },
  },
  {
    id: 'tecnologia',
    nom: 'Tecnologia',
    icon: '💻',
    prompts: {
      basic: 'Ets un professor de tecnologia per a persones no tècniques. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un enginyer de software. Dona un consell intermedi sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un arquitecte de sistemes sènior. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com protegir les contrasenyes amb un gestor de contrasenyes',
        'com evitar estafes i phishing al correu electrònic',
        'per què és important actualitzar el sistema operatiu',
        'com fer còpies de seguretat dels teus arxius importants',
        'com millorar la velocitat del mòbil netejant la caché',
        'consells per a una bona higiene digital (privacitat a les xarxes)',
        'com usar Google de manera més eficient amb cerca avançada',
        'com configurar l\'autenticació en dos factors (2FA)',
        'per què cal desconnectar-se del wifi públic per seguretat',
        'com organitzar millor els arxius al núvol (Drive, iCloud)',
      ],
      intermediate: [
        'automatització de tasques repetitives amb scripts de shell',
        'com usar Git de manera efectiva en un projecte en solitari',
        'productivitat amb eines com Notion, Obsidian o Linear',
        'introducció als contenidors Docker per a desenvolupadors',
        'com configurar un entorn de desenvolupament local eficient',
        'bones pràctiques de seguretat en APIs REST',
        'com depurar errors de xarxa amb les DevTools del navegador',
        'introducció als webhooks i com integrar serveis web',
        'com llegir i aprofitar la documentació tècnica d\'una API',
        'ús de variables d\'entorn per gestionar secrets en projectes',
      ],
      advanced: [
        'patrons de disseny per a sistemes distribuïts (CQRS, Event Sourcing)',
        'optimització de consultes en bases de dades relacionals',
        'estratègies de caché a múltiples nivells (CDN, Redis, memòria)',
        'seguretat avançada: OWASP Top 10 i com mitigar-los',
        'observabilitat: traces distribuïdes, mètriques i logs centralitzats',
        'arquitectura de microserveis: quan té sentit i quan no',
        'kubernetes: gestió de pods, services i ingress controllers',
        'optimització de rendiment en aplicacions React/Next.js',
        'CI/CD avançat: blue-green deployments i feature flags',
        'anàlisi de complexitat algorítmica i optimització de codi crític',
      ],
    },
  },
  {
    id: 'huerto',
    nom: 'Huerto Ecològic',
    icon: '🌱',
    prompts: {
      basic: 'Ets un agricultor ecològic amb experiència. Dona un consell bàsic per a un principiant sobre: {topic}. Respon en Català, en 3-5 frases pràctiques.',
      intermediate: 'Ets un expert en permacultura. Dona un consell intermedi per a algú amb experiència bàsica en jardineria sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un agrònom especialitzat en agricultura regenerativa. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'quines plantes aromàtiques són les millors per al balcó',
        'com preparar la terra d\'un test per plantar de zero',
        'quanta aigua necessiten les tomaqueres a l\'estiu',
        'com sembrar enciams i tindre collita tot l\'any',
        'per què és important el drenatge en els tests',
        'quines plantes s\'adapten millor a l\'ombra parcial',
        'com fer un petit compostador casolà amb restes orgàniques',
        'quan i com trasplantar una plàntula al seu test definitiu',
        'com reconèixer si a una planta li falta o li sobra aigua',
        'els errors més comuns d\'un principiant en l\'hort',
      ],
      intermediate: [
        'rotació de cultius per evitar l\'esgotament del sòl',
        'compostatge avançat: relació carboni/nitrogen òptima',
        'control de pugons i àcars amb preparats naturals',
        'associació de cultius beneficiosa: tomàquets, alfàbrega i ceba',
        'com fer un acolxat (mulching) eficient per conservar la humitat',
        'introducció al cultiu en bancals elevats (raised beds)',
        'preparació de te de compost per fertilitzar de manera natural',
        'com gestionar les malalties fúngiques sense productes químics',
        'sembra per lluna: fonaments i aplicació pràctica',
        'com fer esqueixos i multiplicar plantes de manera vegetativa',
      ],
      advanced: [
        'biofertilitzants: lactobacilos, trichoderma i micorizes',
        'tècnica de sòl viu: fungus networks i biologia del sòl',
        'sistemes agroforestals: integrar arbres fruiters en l\'hort',
        'permacultura avançada: zones, sectors i disseny de paisatge productiu',
        'agricultura sinergètica de Masanobu Fukuoka aplicada a l\'hort urbà',
        'anàlisi de sòl avançada: pH, CIC, i nutrients disponibles',
        'biodynamia: preparats 500 i 501 i la seua aplicació',
        'disseny de sistemes d\'irrigació per degoteig eficients',
        'producció de llavors pròpies i conservació del patrimoni genètic',
        'integració de bestiar menor (gallines, cucs) en sistemes d\'hort tancat',
      ],
    },
  },
  {
    id: 'estructures',
    nom: 'Estructures Metàl·liques',
    icon: '🏗️',
    prompts: {
      basic: 'Ets un tècnic en construcció metàl·lica. Dona un consell bàsic per a algú que s\'inicia sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un enginyer estructural. Dona un consell intermedi per a tècnics amb experiència sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un enginyer estructural sènior especialitzat en estructures metàl·liques. Dona un consell avançat sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'els tipus de perfils metàl·lics més comuns (HEB, IPE, UPN)',
        'com llegir un plànol estructural bàsic',
        'la diferència entre acer S235 i S355',
        'les eines bàsiques d\'un taller de construcció metàl·lica',
        'com mesurar i marcar perfils metàl·lics correctament',
        'les normes bàsiques de seguretat en un taller metàl·lic',
        'conceptes bàsics de soldadura: tipus i aplicacions',
        'per què és important la protecció anticorrosió (galvanitzat, pintura)',
        'la diferència entre una unió soldada i una cargolada',
        'com interpretar una fulla d\'especificació tècnica d\'un perfil',
      ],
      intermediate: [
        'càlcul de moment flector en biga simplement recolzada',
        'disseny de unions cargolades per a estructures de classe 2',
        'protecció al foc d\'estructures metàl·liques: normativa CTE-SI',
        'el fenomen del vinclament (pandeo) i com prevenir-lo',
        'soldadura en angle: dimensions, control de qualitat i assajos',
        'coordinació entre estructura metàl·lica i façana',
        'càlcul de plaques base i ancoratges a fonamentació',
        'introducció al programari CYPE per a càlcul d\'estructures',
        'unitats i codificació en plànols d\'estructura metàl·lica',
        'el paper de l\'enginyer de control de qualitat en obra metàl·lica',
      ],
      advanced: [
        'anàlisi no lineal geomètrica i material en estructures metàl·liques',
        'disseny sísmic d\'estructures metàl·liques: ductilitat i classes de secció',
        'fatiga en estructures metàl·liques: càlcul i categories de detall',
        'optimització topològica amb Grasshopper i Karamba3D',
        'estructures tensegritat i cable-stayed: principis de disseny',
        'modelització per elements finits (FEM) d\'unions complexes',
        'disseny de cobertes lleugeres d\'acer: formes funiculars',
        'connexions semi-rígides: comportament moment-rotació i implicacions',
        'control de qualitat avançat en soldadura: END i certificació EN 1090',
        'BIM aplicat a estructures metàl·liques: Tekla Structures i IFC',
      ],
    },
  },
  {
    id: 'ia',
    nom: 'Intel·ligència Artificial',
    icon: '🤖',
    prompts: {
      basic: 'Ets un divulgador de IA per al gran públic. Dona un consell pràctic sobre: {topic}. Respon en Català, en 3-5 frases senzilles.',
      intermediate: 'Ets un professional de IA. Dona un consell intermedi sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un investigador en IA. Dona un consell avançat i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com escriure prompts clars per obtenir millors respostes de ChatGPT o Claude',
        'com usar la IA per resumir documents llargs',
        'com evitar que la IA t\'inventi informació (al·lucinacions)',
        'com usar la IA per aprendre un tema nou de manera guiada',
        'consells per usar la IA de manera segura i privada',
        'com usar la IA per corregir i millorar textos en català',
        'les millors eines d\'IA gratuïtes per a ús quotidià',
        'com usar la IA per preparar presentacions i reunions',
        'per què és important verificar sempre la informació que dona la IA',
        'com usar la IA per crear contingut a les xarxes socials',
      ],
      intermediate: [
        'tècniques avançades de prompt engineering: chain-of-thought i few-shot',
        'com avaluar i comparar models d\'IA per a una tasca específica',
        'integració d\'IA en fluxos de treball empresarials amb APIs',
        'casos d\'ús de la IA en anàlisi de dades i reporting automatitzat',
        'com usar embedding models per a cerca semàntica',
        'introducció als agents d\'IA i quan té sentit usar-los',
        'com construir un pipeline RAG senzill per als teus documents',
        'avaluació de la qualitat de les respostes d\'un LLM',
        'IA multimodal: com usar models amb imatges i documents',
        'com gestionar costos d\'API d\'IA en producció',
      ],
      advanced: [
        'fine-tuning de models de llenguatge: quan té sentit vs. prompting',
        'arquitectura de sistemes RAG avançats: reranking i query expansion',
        'agents autònoms multi-pas: planificació i execució d\'eines',
        'avaluació sistemàtica de LLMs: benchmarks, evals i mètriques',
        'optimització d\'inferència: quantització, batching i KV cache',
        'seguretat en sistemes d\'IA: prompt injection i jailbreaking',
        'tendències actuals en recerca: models de raonament i test-time compute',
        'arquitectures mixture-of-experts (MoE) i les seues implicacions',
        'construcció de pipelines d\'entrenament continu (RLHF/DPO)',
        'memòria a llarg termini en agents: vector stores i grafos de coneixement',
      ],
    },
  },
  {
    id: 'kitesurf',
    nom: 'Kitesurf',
    icon: '🪁',
    prompts: {
      basic: 'Ets un instructor de kitesurf certificat IKO. Dona un consell pràctic i segur per a un principiant sobre: {topic}. Respon en Català, en 3-5 frases clares.',
      intermediate: 'Ets un instructor de kitesurf amb 10 anys d\'experiència. Dona un consell intermedi per a algú que ja sap navegar però vol millorar sobre: {topic}. Respon en Català, en 3-5 frases.',
      advanced: 'Ets un rider professional de kitesurf i entrenador de competició. Dona un consell avançat i tècnic sobre: {topic}. Respon en Català, en 3-5 frases tècniques.',
    },
    topics: {
      basic: [
        'com interpretar les condicions de vent per a un principiant (direcció, velocitat)',
        'les zones de seguretat al voltant del cometa (zona de poder i zona neutra)',
        'com muntar i desmontar l\'equip de kitesurf de manera segura',
        'la tècnica del body drag per recuperar la taula a l\'aigua',
        'com activar el sistema de seguretat (quick release) correctament',
        'per què és perillós fer kitesurf amb vent off-shore',
        'com pilotar el cometa en la zona de vent (finestra de vol)',
        'els senyals de mà per comunicar-se a la platja',
        'com escollir la talla de cometa adequada per al teu pes i el vent',
        'les regles de prioritat entre riders al water',
      ],
      intermediate: [
        'la tècnica del water start: passos i errors comuns',
        'com fer un halte (stop) controlat al water',
        'tècnica del tack (canvi de direcció cap al vent)',
        'tècnica del jibe (canvi de direcció amb el vent)',
        'com generar velocitat i mantenir el contakt amb l\'aigua',
        'com navegar en upwind (contra el vent)',
        'el relaunch del cometa des de l\'aigua',
        'com usar la barra per controlar la potència del cometa (sheet in/out)',
        'tècnica de riding amb taula twintip en waves',
        'com preparar i gestionar un primer salt petit',
      ],
      advanced: [
        'tècnica del jump: pop, timing i control del cometa en aire',
        'el megaloop: iniciació segura i progressió',
        'tricks unhooked bàsics: railey i back roll unhooked',
        'wave riding amb kitesurf: lectura de l\'onada i timing',
        'kitesurf amb foil: diferències tècniques i adaptació',
        'tècnica del board-off en salts',
        'com optimitzar el trim i la posició de les ancoratges del bar',
        'progressió en kiteloop: control del pull i seguretat',
        'com entrenar kitesurf fora de l\'aigua (visualització, gym)',
        'preparació per a competicions de freestyle: judging criteria',
      ],
    },
  },
]

export const DIFFICULTIES = [
  { id: 'basic', label: 'Bàsic' },
  { id: 'intermediate', label: 'Intermedi' },
  { id: 'advanced', label: 'Avançat' },
]

export function buildPrompt(category, difficulty, topic = null) {
  const chosen = topic ?? category.topics[difficulty][
    Math.floor(Math.random() * category.topics[difficulty].length)
  ]
  return category.prompts[difficulty].replace('{topic}', chosen)
}
